baseurl = "http://www.magdalenabennett.com"
title = "maibennett"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "maibennett"
googleAnalytics = "UA-102578779-3"
enableEmoji = true

[params]
    author = "Magdalena Bennett"
    description = "Magdalena Bennett's website"
    keywords = "research, personal"
    info = "PhD candidate and #rstats enthusiast"
    avatarurl = "images/mai_bw.jpg"
    footercontent = ""

    dateformat = "April 2, 2019"

    hideCredits = false
    hideCopyright = false

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Use inverted colors
    inverted = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = ["css/css_style.css"]

[taxonomies]
  series = "series"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/maibennett/"
[[params.social]]
    name = "Spotify"
    icon = "fab fa-spotify"
    weight = 2
    url = "https://open.spotify.com/user/11120745477?si=qLO1ptujQ2Wm78B8_NCMww"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/maibennett/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/magdalena-bennett-9b18b816/"


[languages]
    [languages.en]
        languagename = "English"

        [[languages.en.menu.main]]
        name = "About"
        weight = 1
        url = "/about/"

        [[languages.en.menu.main]]
        name = "Research"
        weight = 2
        url = "/research/"
        
        [[languages.en.menu.main]]
        name = "Resources"
        weight = 3
        url = "/resources/"
        
        [[languages.en.menu.main]]
        name = "Random Stuff"
        weight = 4
        url = "/random/"
        
        [[languages.en.menu.main]]
        name = "#COVID-19"
        weight = 5
        url = "/covid/"

        [[languages.en.menu.main]]
        name = "Contact me"
        weight = 6
        url = "/contact/"
